---
- name: Install Docker Engine on remote machine
  hosts: vagrant
  remote_user: vagrant
  vars_files:
    - playbook_vars/docker_vars.yaml
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update-cache: true
        upgrade: full
        cache_valid_time: 3600

    - name: Install packages
      apt:
        name: "{{item}}"
        update-cache: true
      loop:
         - ca-certificates
         - curl
         - software-properties-common

    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings/
        state: directory
        mode: 0755

    - name: Add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add docker repository
      apt_repository:
        filename: docker
        repo: deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | lower }} stable
        state: present
     
    - name: Install latest version of docker engine
      apt:
        name: "{{ item }}"
        update-cache: true
      loop: "{{ docker_engine }}"

    - name: Create group for docker
      group:
        name: docker
        state: present
    
    - name: Add user to the group
      user:
        name: vagrant
        groups: docker
        append: yes

...
