---
- name: Copy jar file to the remote host and run it in Docker container
  hosts: vagrant
  remote_user: vagrant
  vars_files:
    - playbook_vars/run_app_in_container_vars.yaml
  vars:
    - copydir: files_to_copy
  become: true

  tasks:
    - name: Create app folder
      file:
        path: "{{ workdir }}"
        state: directory
    
    - name: Copy Docker file
      copy:
        src: "{{files_to_copy}}/Dockerfile"
        dest: "{{ workdir }}"
    
    - name: Copy jar file
      copy:
        src: "{{files_to_copy}}/AnsibleTestApp-0.0.1-SNAPSHOT.jar"
        dest: "{{ workdir }}/app.jar"

    - name: Copy application.yaml file
      copy:
        src: "{{files_to_copy}}/application.properties"
        dest: "{{ workdir }}/application.properties"

    - name: Build an image from Dockerfile
      community.docker.docker_image:
        build:
          path: "{{ workdir }}"
        name: test_app
        source: build

    - name: Start container using created image
      community.docker.docker_container:
        name: java-app
        image: test_app
        state: started
        ports:
          - "8081:8081"

...